/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllDependency: typeof import('./components/icon/allDependency.vue')['default']
    Arrow: typeof import('./components/icon/arrow.vue')['default']
    Attribute: typeof import('./pages/bp/component/attribute.vue')['default']
    Ban: typeof import('./pages/bp/component/ban.vue')['default']
    C: typeof import('./components/icon/c.vue')['default']
    'C++': typeof import('./components/icon/c++.vue')['default']
    Choice: typeof import('./pages/bp/component/choice.vue')['default']
    CPlus: typeof import('./components/icon/cPlus.vue')['default']
    Dependency: typeof import('./components/icon/dependency.vue')['default']
    DependencyGraph: typeof import('./components/dependencyGraph.vue')['default']
    DependencyGrapj: typeof import('./components/dependencyGrapj.vue')['default']
    Efficiency: typeof import('./components/icon/efficiency.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Exe: typeof import('./components/icon/exe.vue')['default']
    Folder: typeof import('./components/icon/folder.vue')['default']
    Genie: typeof import('./pages/bp/component/genie.vue')['default']
    GenieEazy: typeof import('./components/genieEazy.vue')['default']
    H: typeof import('./components/icon/h.vue')['default']
    LineLayout: typeof import('./components/icon/lineLayout.vue')['default']
    Linux: typeof import('./components/icon/linux.vue')['default']
    Navigation: typeof import('./components/navigation.vue')['default']
    NewPackage: typeof import('./components/icon/newPackage.vue')['default']
    Round: typeof import('./pages/bp/component/Round.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shell: typeof import('./components/icon/shell.vue')['default']
    Source: typeof import('./components/icon/source.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    Tip: typeof import('./components/tip.vue')['default']
    Title: typeof import('./components/title.vue')['default']
    UpdateTag: typeof import('./components/updateTag.vue')['default']
  }
}
